### ISSUE TITLE
Logo/Proposal

### ISSUE THREAD

**Issue by jbeguna04** [HurryPeng/FragMem#1]
Greetings, Im a graphics designer here on Github and I would like to ask for your permission to design for your logo/icon that you maybe used for your future plans in your project. I want to help open source projects by designing logos or banners for there project. Thank you for your time reading this

Best regards
-jbeguna04

**Comment by HurryPeng** [comment]
Thank you for offering your help as a specialist in icon designing just when I need one, but unluckily I've just asked one of my friends to help me do it, so it would be a little bit embarrasing this time. Seeing your fascinating works, I will certainly welcome you to help me design other icons the next time if you would like to. Thank you all the same for your passion and I feel very glad to meet you.

**Comment by jbeguna04** [comment]
Thank you also for your time viewing this issue. I will be honored to help you next time around
Please contact me on @jibbieeguna@yahoo.com
